name: Python CI

on:
  push:
    paths:
      - 'python-app/src/**'
      - 'python-app/Dockerfile'
      - '.github/workflows/python-ci.yml'
    branches:
      - master

jobs:
  build:
    runs-on: arc-runner-set
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

